color = '\33[1;35m'
clear = '\33[0;0m'
n = int(input('Digite um número inteiro: '))

print(color)
print('Minha Resolução: ', end='')
print(clear)

print('Tabuada do {}' .format(n))
print('{} * 0 = {}'.format(n, n*0))
print('{} * 1 = {}'.format(n, n*1))
print('{} * 2 = {}'.format(n, n*2))
print('{} * 3 = {}'.format(n, n*3))
print('{} * 4 = {}'.format(n, n*4))
print('{} * 5 = {}'.format(n, n*5))
print('{} * 6 = {}'.format(n, n*6))
print('{} * 7 = {}'.format(n, n*7))
print('{} * 8 = {}'.format(n, n*8))
print('{} * 9 = {}'.format(n, n*9))
print('{} * 10 = {}'.format(n, n*10))

print(color)
print('Resolução do Professor: ', end='')
print(clear)
print('-' * 20)
print('Tabuada do {}' .format(n))
print('{} * {:2} = {:2}'.format(n, 1, n*1))
print('{} * {:2} = {:2}'.format(n, 2, n*2))
print('{} * {:2} = {:2}'.format(n, 3, n*3))
print('{} * {:2} = {:2}'.format(n, 4, n*4))
print('{} * {:2} = {:2}'.format(n, 5, n*5))
print('{} * {:2} = {:2}'.format(n, 6, n*6))
print('{} * {:2} = {:2}'.format(n, 7, n*7))
print('{} * {:2} = {:2}'.format(n, 8, n*8))
print('{} * {:2} = {:2}'.format(n, 9, n*9))
print('{} * {:2} = {:2}'.format(n, 10, n*10))
